### Name: Bhargavi Poyekar
### BE COMPS - Batch C
### UID: 2018130040

# AISC LAB 6



## AIM: To implement Fuzzy Sets and Fuzzy Relations

## CODE:

In [26]:
import numpy as np

###Fuzzy Sets


In [8]:
An=[0.8,0.2,0.5,0.7]
Ad=[1,3,5,7]

Bn=[0.3,0.4,0.1,0.9]
Bd=[1,3,5,7]

print("Fuzzy Set A: ")
print("{ ",end="")
for i in range(len(An)-1):
  print(f'{An[i]}/{Ad[i]} + ', end="") 

print(f'{An[len(An)-1]}/{Ad[len(An)-1]}',end="")
print("}")

print("\nFuzzy Set B: ")
print("{ ",end="")
for i in range(len(Bn)-1):
  print(f'{Bn[i]}/{Bd[i]} + ', end="") 

print(f'{Bn[len(Bn)-1]}/{Bd[len(Bn)-1]}',end="")
print("}")




Fuzzy Set A: 
{ 0.8/1 + 0.2/3 + 0.5/5 + 0.7/7}

Fuzzy Set B: 
{ 0.3/1 + 0.4/3 + 0.1/5 + 0.9/7}


### Union 

In [9]:
print("Union of A and B = max[An(x), Bn(x)]: ")
print("{ ",end="")
for i in range(len(An)-1):
  print(f'{max(An[i],Bn[i])}/{Ad[i]} + ', end="") 

print(f'{max(An[len(An)-1],Bn[len(Bn)-1])}/{Ad[len(An)-1]}',end="")
print("}")



Union A and B = max[An(x), Bn(x)]: 
{ 0.8/1 + 0.4/3 + 0.5/5 + 0.9/7}


###Intersection

In [10]:
print("Intersection of A and B = min[An(x), Bn(x)]: ")
print("{ ",end="")
for i in range(len(An)-1):
  print(f'{min(An[i],Bn[i])}/{Ad[i]} + ', end="") 

print(f'{min(An[len(An)-1],Bn[len(Bn)-1])}/{Ad[len(An)-1]}',end="")
print("}")



Intersection of A and B = min[An(x), Bn(x)]: 
{ 0.3/1 + 0.2/3 + 0.1/5 + 0.7/7}


### Complement 

In [13]:
# Complement of A
print("Complement of A = 1-An(x): ")
print("{ ",end="")
for i in range(len(An)-1):
  print(f'{round(1-An[i],1)}/{Ad[i]} + ', end="") 

print(f'{round(1-An[len(An)-1],1)}/{Ad[len(An)-1]}',end="")
print("}")

Complement of A = 1-An(x): 
{ 0.2/1 + 0.8/3 + 0.5/5 + 0.3/7}


In [14]:
# Complement of B
print("Complement of B = 1-Bn(x): ")
print("{ ",end="")
for i in range(len(Bn)-1):
  print(f'{round(1-Bn[i],1)}/{Bd[i]} + ', end="") 

print(f'{round(1-Bn[len(Bn)-1],1)}/{Bd[len(Bn)-1]}',end="")
print("}")

Complement of B = 1-Bn(x): 
{ 0.7/1 + 0.6/3 + 0.9/5 + 0.1/7}


### Difference

In [17]:
# A|B
print("A|B = min[An(x), (1-Bn(x))]") # A intersection complement of B
print("{ ",end="")
for i in range(len(An)-1):
  print(f'{min(An[i],round(1-Bn[i],1))}/{Ad[i]} + ', end="") 

print(f'{min(An[len(An)-1],round(1-Bn[len(Bn)-1],1))}/{Ad[len(An)-1]}',end="")
print("}")

A|B = min[An(x), (1-Bn(x))]
{ 0.7/1 + 0.2/3 + 0.5/5 + 0.1/7}


In [18]:
# B|A
print("B|A = min[Bn(x), (1-An(x))]") # B intersection complement of A
print("{ ",end="")
for i in range(len(An)-1):
  print(f'{min(Bn[i],round(1-An[i],1))}/{Ad[i]} + ', end="") 

print(f'{min(Bn[len(Bn)-1],round(1-An[len(An)-1],1))}/{Ad[len(An)-1]}',end="")
print("}")

B|A = min[Bn(x), (1-An(x))]
{ 0.2/1 + 0.4/3 + 0.1/5 + 0.3/7}


### Fuzzy Relations

In [34]:
# Three fuzzy sets
Rn = [0.5, 0.8, 0.4, 0.2]
Rd = [30, 60, 100, 120]

In = [0.1, 0.5, 0.7, 0.9, 0.3, 1.0]
Id = [20, 40, 60, 80, 100, 120]

Nn = [0.23, 0.54, 0.87, 0.45]
Nd = [500, 1000, 1500, 1800]

print("Fuzzy Set R: ")
print("{ ",end="")
for i in range(len(Rn)-1):
  print(f'{Rn[i]}/{Rd[i]} + ', end="") 

print(f'{Rn[len(Rn)-1]}/{Rd[len(Rn)-1]}',end="")
print("}")

print("\nFuzzy Set I: ")
print("{ ",end="")
for i in range(len(In)-1):
  print(f'{In[i]}/{Id[i]} + ', end="") 

print(f'{In[len(In)-1]}/{Id[len(In)-1]}',end="")
print("}")

print("\nFuzzy Set N: ")
print("{ ",end="")
for i in range(len(Nn)-1):
  print(f'{Nn[i]}/{Nd[i]} + ', end="") 

print(f'{Nn[len(Nn)-1]}/{Nd[len(Nn)-1]}',end="")
print("}")

Fuzzy Set R: 
{ 0.5/30 + 0.8/60 + 0.4/100 + 0.2/120}

Fuzzy Set I: 
{ 0.1/20 + 0.5/40 + 0.7/60 + 0.9/80 + 0.3/100 + 1.0/120}

Fuzzy Set N: 
{ 0.23/500 + 0.54/1000 + 0.87/1500 + 0.45/1800}


### R to N relation

In [35]:
# R` = R X I (Cartesian Product)

Rp = []
for r in Rn:
  row=[]
  for i in In:
    row.append(min(r, i))
  Rp.append(row)

Rp

[[0.1, 0.5, 0.5, 0.5, 0.3, 0.5],
 [0.1, 0.5, 0.7, 0.8, 0.3, 0.8],
 [0.1, 0.4, 0.4, 0.4, 0.3, 0.4],
 [0.1, 0.2, 0.2, 0.2, 0.2, 0.2]]

In [36]:
# S` = I X N (Cartesian Product)

Sp = []
for i in In:
  row=[]
  for n in Nn:
    row.append(min(n, i))
  Sp.append(row)
  
Sp

[[0.1, 0.1, 0.1, 0.1],
 [0.23, 0.5, 0.5, 0.45],
 [0.23, 0.54, 0.7, 0.45],
 [0.23, 0.54, 0.87, 0.45],
 [0.23, 0.3, 0.3, 0.3],
 [0.23, 0.54, 0.87, 0.45]]

In [37]:
Rp = np.array(Rp)
Sp = np.array(Sp)


### Max-min composition


In [38]:
SpT= np.transpose(Sp)
min_max = []
for r in range(len(Rp)):
  for k in range(len(SpT)):
    row = []
    for s in range(len(SpT[0])):
      row.append(min(Rp[r][s], SpT[k][s]))
    min_max.append(max(row))
T = []
row = []
for i in range(len(min_max)):
  if i == len(min_max)-1:
    T.append(row)
  if i%4 == 0 and i!=0:
    T.append(row)
    row = []
  row.append(min_max[i])
print(np.array(T))

[[0.23 0.5  0.5  0.45]
 [0.23 0.54 0.8  0.45]
 [0.23 0.4  0.4  0.4 ]
 [0.2  0.2  0.2  0.2 ]]


### Max-product Composition

In [39]:
max_prod = []
for r in range(len(Rp)):
  for k in range(len(SpT)):
    row = []
    for s in range(len(SpT[0])):
      row.append(Rp[r][s]*SpT[k][s])
    max_prod.append(max(row))
T = []
row = []
for i in range(len(max_prod)):
  if i == len(max_prod)-1:
    T.append(row)
  if i%4 == 0 and i!=0:
    T.append(row)
    row = []
  row.append(max_prod[i])
print(np.array(T))

[[0.115 0.27  0.435 0.225]
 [0.184 0.432 0.696 0.36 ]
 [0.092 0.216 0.348 0.18 ]
 [0.046 0.108 0.174 0.09 ]]
